import os
import sys
import logging
import subprocess
# Uses the modern, production-ready GenAI library
from google import genai

# Local module imports
from cli import main as cli_runner
from modules.governance_node import GovernanceNode
from modules.health_monitor import HealthMonitor
from modules.asset_core import AssetManager

def setup_logger():
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )
    return logging.getLogger(__name__)

logger = setup_logger()

class DockerHubBot:
    def __init__(self):
        pass

    def bootstrap_assets(self):
        """Initializes the autonomous ecosystem and starts the execution loop."""
        logger.info("Initializing Docker-Hub-Bot Autonomous Ecosystem...")

        governance = GovernanceNode()
        health = HealthMonitor()

        active_nodes = ["DockerHub", "GitHub", "Telegram", "Slack"]
        health.check_platform_connectivity(active_nodes)

        try:
            if len(sys.argv) > 1:
                logger.info(f"Executing command: {' '.join(sys.argv[1:])}")
                cli_runner()
            else:
                logger.info("No specific arguments detected. Triggering standard asset sync...")
                AssetManager().sync_ecosystem()
                logger.info("Heartbeat sync complete. System awaiting commands.")
                
        except Exception as e:
            logger.error(f"Critical System Failure in Ecosystem Loop: {e}")
            sys.exit(1)

    def brain_search_and_install(self, query):
        """Brain Module: Gemini searches, validates, and provisions environments."""
        print(f"[*] Brain Module analyzing Docker Hub for: {query}")

        # BYPASS CHECK: Gracefully exit this module if the user hasn't provided a key
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            logger.warning("GEMINI_API_KEY environment variable is missing. Skipping AI generation.")
            print("[!] Gemini feature skipped: No API key provided.")
            return

        prompt = f"""
        You are a systems architecture bot. Search for the optimal official Docker image for '{query}'

        Generate a robust configuration including:
        1. A 'Dockerfile' utilizing strict layer caching optimizations.
        2. A '.dockerignore' to prevent unnecessary payload bloat.
        3. A 'docker-compose.yml' file to securely orchestrate the environment.
        OUTPUT ONLY the raw file contents wrapped in tags like ---DOCKERFILE---, ---COMPOSE---, etc.
        """

        try:
            # Initializes the modern client with the key cleanly
            client = genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model='gemini-1.5-flash',
                contents=prompt
            )

            print("[*] Configuration Generated by Gemini. Provisioning...")

            with open("unified_infrastructure.yaml", "w") as f:
                f.write(response.text)

            print("[*] Spinning up multi-container environment...")
            
        except Exception as e:
            logger.error(f"Failed to communicate with Gemini API: {e}")


if __name__ == "__main__":
    bot = DockerHubBot()
    bot.bootstrap_assets()
    bot.brain_search_and_install("high-throughput rust development environment")
